jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: chocolateen
          name: "Hugo"
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: vaugie_g
          name: "Garance"
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: i_dont_know
          name: "Jeremy"
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: nasso
          name: "Nassim"
          password: ${USER_NASSO_PASSWORD}


  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "chocolateen"
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Read"
            assignments:
              - "i_dont_know"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Read"
              - "Job/Create"
              - "Job/Configure"
              - "Job/Delete"
              - "Job/Move"
              - "Job/Cancel"
            assignments:
              - "vaugie_g"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Overall/Read"
              - "Job/Workspace"
              - "Job/Read"
            assignments:
              - "nasso"


jobs:
  - script: >
      folder('Tools') {
        description('Folder for miscellaneous tools.')
        displayName('Tools')
      }
      freeStyleJob('Tools/clone-repository') {
        parameters {
          stringParam('GIT_REPOSITORY_URL', '', 'Git URL of the repository to clone')
        }
        steps {
          shell('git clone $GIT_REPOSITORY_URL')
        }
        wrappers {
          preBuildCleanup()
        }
      }
      freeStyleJob('Tools/SEED') {
        parameters {
          stringParam('GITHUB_NAME', '', 'GitHub repository owner/repo_name (e.g.: "EpitechIT31000/chocolatine")')
          stringParam('DISPLAY_NAME', '', 'Display name for the job')
        }
        steps {
          dsl {
            text('''
            job("Tools/$DISPLAY_NAME") {
              scm {
                github("$GITHUB_NAME")
              }
              triggers {
                scm('H/1 * * * *')
              }
              wrappers {
                preBuildCleanup()
              }
              steps {
                shell('make fclean')
                shell('make')
                shell('make tests_run')
                shell('make clean')
              }
            }'''.stripIndent())
          }
        }
      }